ci debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -170,7 +170,7 @@ jobs:
 
   test-e2e-podman:
     runs-on: ubuntu-${{ matrix.ubuntu-version }}
-    needs: test-make-all
+    #needs: test-make-all
     services:
       registry:
         image: registry:2
@@ -196,18 +196,35 @@ jobs:
             location = 'localhost:80'
           insecure = true" | tee ~/.config/containers/registries.conf.d/insecure-localhost.conf
           systemctl --user restart podman
-      - name: Restore image cache
-        uses: actions/cache/restore@v4
-        with:
-          path: /tmp/ci-images
-          key: 'ci-test-${{ github.sha }}'
-          fail-on-cache-miss: true
-      - name: Import cached images
-        run: |
           set -x
-          ls -la /tmp/ci-images
-          find /tmp/ci-images -type f -name '*.tar' -exec podman load -i '{}' \;
-          podman images
+          set +e
+          id -a
+          echo $HOME
+          ls -la /home
+          ls -la /home/*
+          sudo apt-get update
+          sudo apt-get dist-upgrade -y
+          podman info
+          podman system migrate
+          podman info
+          podman system reset -f
+          podman info
+          systemctl --user restart podman
+          set -e
+          set +x
+
+#      - name: Restore image cache
+#        uses: actions/cache/restore@v4
+#        with:
+#          path: /tmp/ci-images
+#          key: 'ci-test-${{ github.sha }}'
+#          fail-on-cache-miss: true
+#      - name: Import cached images
+#        run: |
+#          set -x
+#          ls -la /tmp/ci-images
+#          find /tmp/ci-images -type f -name '*.tar' -exec podman load -i '{}' \;
+#          podman images
       - uses: actions/checkout@v4
         with:
           submodules: true
